"""Questionnaire definition - AI-guided interview with skip logic.

Each question: key (profile field), kind (number/select/boolean/text),
options, next routing, skip conditions evaluated against current answers.
"""
from __future__ import annotations

STATES = ["Andhra Pradesh", "Telangana", "Tamil Nadu", "Karnataka", "Kerala", "Maharashtra",
          "Gujarat", "Rajasthan", "Uttar Pradesh", "Madhya Pradesh", "Bihar", "West Bengal",
          "Odisha", "Assam", "Punjab", "Haryana", "Delhi", "Chhattisgarh", "Jharkhand",
          "Himachal Pradesh", "Uttarakhand", "Goa", "Jammu and Kashmir"]

OCCUPATIONS = [
    {"value": "farmer", "label": "Farmer"},
    {"value": "agriculture labourer", "label": "Agriculture labourer"},
    {"value": "student", "label": "Student"},
    {"value": "employee", "label": "Salaried employee"},
    {"value": "self-employed", "label": "Self-employed"},
    {"value": "business", "label": "Business owner"},
    {"value": "daily wage", "label": "Daily wage worker"},
    {"value": "unemployed", "label": "Unemployed / looking for work"},
    {"value": "retired", "label": "Retired"},
    {"value": "housewife", "label": "Homemaker"},
    {"value": "other", "label": "Other"},
]

EDUCATION = [
    {"value": "none", "label": "No formal education"},
    {"value": "primary", "label": "Primary (Class 1-5)"},
    {"value": "secondary", "label": "Secondary (Class 6-10)"},
    {"value": "hs", "label": "Higher secondary (Class 11-12)"},
    {"value": "diploma", "label": "Diploma / ITI"},
    {"value": "graduate", "label": "Graduate"},
    {"value": "postgraduate", "label": "Post-graduate"},
    {"value": "other", "label": "Other"},
]

CATEGORIES = [{"value": "general", "label": "General"}, {"value": "sc", "label": "SC"},
              {"value": "st", "label": "ST"}, {"value": "obc", "label": "OBC"},
              {"value": "ews", "label": "EWS"}, {"value": "minority", "label": "Minority"}]

QUESTIONS = [
    {"key": "age", "kind": "number", "prompt": "What is your age?", "min": 0, "max": 120,
     "options": [], "hint": "Years. This determines pension, education and health schemes.", "skip": []},
    {"key": "gender", "kind": "select", "prompt": "What is your gender?",
     "options": [{"value": "male", "label": "Male"}, {"value": "female", "label": "Female"}, {"value": "other", "label": "Other"}],
     "hint": "Many schemes are specific to women.", "skip": []},
    {"key": "state", "kind": "select", "prompt": "Which state do you live in?",
     "options": [{"value": s, "label": s} for s in STATES],
     "hint": "Central + state schemes will be matched.", "skip": []},
    {"key": "district", "kind": "text", "prompt": "Which district?", "options": [],
     "hint": "District-level schemes use this.", "skip": []},
    {"key": "occupation", "kind": "select", "prompt": "What is your primary occupation?",
     "options": OCCUPATIONS, "hint": "We will tailor questions around this.", "skip": []},
    {"key": "land_owned_acres", "kind": "number", "prompt": "How much agricultural land do you own?",
     "min": 0, "max": 1000, "options": [], "hint": "In acres. 0 if none.",
     "skip": [{"field": "occupation", "op": "not_in", "value": ["farmer", "agriculture labourer"]}]},
    {"key": "is_marginal_farmer", "kind": "boolean", "prompt": "Are you a small/marginal farmer (own less than 2 hectares)?",
     "options": [], "hint": "Defines PM-KISAN eligibility.",
     "skip": [{"field": "occupation", "op": "not_in", "value": ["farmer", "agriculture labourer"]}]},
    {"key": "education", "kind": "select", "prompt": "What is your highest education level?",
     "options": EDUCATION, "hint": "Drives scholarship & skill schemes.", "skip": []},
    {"key": "student_degree", "kind": "select",
     "prompt": "Which course are you pursuing?",
     "options": [{"value": "engineering", "label": "Engineering / B.Tech"},
                 {"value": "medical", "label": "Medical"},
                 {"value": "law", "label": "Law"},
                 {"value": "commerce", "label": "Commerce / B.Com"},
                 {"value": "arts", "label": "Arts / Humanities"},
                 {"value": "science", "label": "Science"},
                 {"value": "other", "label": "Other"}],
     "hint": "For student scholarships.",
     "skip": [{"field": "occupation", "op": "not_in", "value": ["student"]}]},
    {"key": "annual_income", "kind": "number", "prompt": "What is your family's annual income?",
     "min": 0, "max": 100000000, "options": [], "hint": "In rupees. Most welfare schemes cap at ₹1-8 lakh.", "skip": []},
    {"key": "category", "kind": "select", "prompt": "Which social category do you belong to?",
     "options": CATEGORIES, "hint": "SC/ST/OBC/EWS categories unlock reservation benefits.", "skip": []},
    {"key": "disability", "kind": "select", "prompt": "Do you have any disability?",
     "options": [{"value": "none", "label": "None"}, {"value": "physical", "label": "Physical"},
                 {"value": "visual", "label": "Visual"}, {"value": "hearing", "label": "Hearing"},
                 {"value": "speech", "label": "Speech"}, {"value": "intellectual", "label": "Intellectual"}],
     "hint": "Unlocks disability pensions and assistive schemes.", "skip": []},
    {"key": "marital_status", "kind": "select", "prompt": "What is your marital status?",
     "options": [{"value": "single", "label": "Single"}, {"value": "married", "label": "Married"},
                 {"value": "widowed", "label": "Widowed"}, {"value": "divorced", "label": "Divorced"}],
     "hint": "Widows have dedicated pension support.", "skip": []},
    {"key": "has_children", "kind": "boolean", "prompt": "Do you have children?",
     "options": [], "hint": "For child education & health schemes.", "skip": [{"field": "age", "op": "lt", "value": 18}]},
    {"key": "children_girl", "kind": "boolean", "prompt": "Do you have a daughter?",
     "options": [], "hint": "Unlocks girl-child savings schemes like Sukanya Samriddhi.",
     "skip": [{"any": [{"field": "has_children", "op": "eq", "value": False},
                       {"field": "age", "op": "lt", "value": 18}]}]},
    {"key": "employment_type", "kind": "select", "prompt": "What best describes your employment?",
     "options": [{"value": "organised", "label": "Organised sector (EPF etc.)"},
                 {"value": "unorganised", "label": "Unorganised / informal"},
                 {"value": "self-employed", "label": "Self-employed"},
                 {"value": "none", "label": "Not employed"}],
     "hint": "Unorganised workers qualify for PM-SYM pension.",
     "skip": [{"field": "occupation", "op": "in", "value": ["retired", "student", "housewife"]}]},
    {"key": "business_type", "kind": "select", "prompt": "What kind of business do you run?",
     "options": [{"value": "retail", "label": "Retail / shop"}, {"value": "manufacturing", "label": "Manufacturing / production"},
                 {"value": "services", "label": "Services"}, {"value": "agri-business", "label": "Agri-business"},
                 {"value": "artisan", "label": "Artisan / crafts"}, {"value": "startup", "label": "Startup / tech"}],
     "hint": "Drives MSME, Mudra and startup loans.",
     "skip": [{"field": "occupation", "op": "not_in", "value": ["self-employed", "business"]}]},
    {"key": "business_years", "kind": "number", "prompt": "How many years has the business been running?",
     "min": 0, "max": 80, "options": [], "hint": "Under 10 years qualifies for Startup India.",
     "skip": [{"field": "occupation", "op": "not_in", "value": ["self-employed", "business"]}]},
    {"key": "is_widow", "kind": "boolean", "prompt": "Are you a widow?",
     "options": [], "hint": "Widow pension schemes apply.",
     "skip": [{"any": [{"field": "gender", "op": "not_in", "value": ["female"]},
                       {"field": "marital_status", "op": "not_in", "value": ["widowed"]}]}]},
    {"key": "has_lpg_connection", "kind": "boolean", "prompt": "Does your household have an LPG gas connection?",
     "options": [], "hint": "Ujjwala gives free connections to poor households.", "skip": []},
    {"key": "has_ration_card", "kind": "boolean", "prompt": "Does your family hold a ration (PDS) card?",
     "options": [], "hint": "Signals BPL eligibility.", "skip": []},
    {"key": "has_house", "kind": "boolean", "prompt": "Does your family own a pucca house?",
     "options": [], "hint": "For PM Awas and housing loans.", "skip": []},
    {"key": "aadhaar_linked", "kind": "boolean", "prompt": "Is your Aadhaar linked to your bank account?",
     "options": [], "hint": "Required for DBT (direct benefit transfer).", "skip": []},
]

SUPPORTED_VOICE = [
    {"code": "en", "label": "English"},
    {"code": "hi", "label": "Hindi"},
    {"code": "te", "label": "Telugu"},
    {"code": "ta", "label": "Tamil"},
    {"code": "kn", "label": "Kannada"},
    {"code": "mr", "label": "Marathi"},
]
