"""Seed data: real Central & State government schemes with structured
eligibility rules consumed by the scoring engine.

Rule shape: {"field"|"any"|"all", "op", "value", "weight", "label", "improve"}
  - field+op+value evaluate profile attributes
  - any/all hold groups of sub-rules (OR / AND)
"""
from __future__ import annotations


def R(**kw):
    return kw


SCHEMES = [
    {
        "code": "PM-KISAN", "name": "PM-KISAN Income Support Scheme",
        "short_name": "PM-KISAN", "ministry": "Ministry of Agriculture & Farmers Welfare",
        "department": "Department of Agriculture & Farmers Welfare", "level": "central",
        "category": "farmer",
        "description": "Direct income support of ₹6,000 per year in three instalments to land-holding farmer families.",
        "benefits": [{"label": "Income support", "detail": "₹6,000 per year", "value": "₹6,000/yr"},
                     {"label": "Instalments", "detail": "Three instalments of ₹2,000", "value": "3× ₹2,000"}],
        "eligibility_rules": [
            R(field="is_farmer", op="boolean", value=True, weight=40,
              label="You are a farmer (cultivating land / agriculture labourer)",
              improve="Eligibility requires you to be engaged in farming."),
            R(field="land_owned_acres", op="gte", value=0, weight=15,
              label="You own cultivable land"),
            R(field="age", op="gte", value=18, weight=10, label="You are 18 or older"),
            R(field="employment_type", op="not_in", value=["organised"], weight=10,
              label="Not in an organised salaried sector", improve="Scheme excludes income-tax payers and organised employees."),
            R(field="annual_income", op="lt", value=1000000, weight=10,
              label="Family income below ₹10 lakh", improve="Keep family income under the limit."),
            R(field="state", op="in", value=["Andhra Pradesh", "Telangana", "Tamil Nadu", "Karnataka", "Kerala", "Maharashtra", "Gujarat", "Rajasthan", "Uttar Pradesh", "Madhya Pradesh", "Bihar", "West Bengal", "Odisha", "Assam", "Punjab", "Haryana", "Delhi", "Chhattisgarh", "Jharkhand", "Himachal Pradesh", "Uttarakhand", "Goa"], weight=5,
              label="Resident of India"),
        ],
        "required_documents": ["Aadhaar", "Land records (Patta/RoR)", "Bank passbook", "Khatauni/land certificate"],
        "amount": "₹6,000 per year", "amount_max": 6000, "duration": "Annual, ongoing",
        "application_time": "10 minutes", "renewal_policy": "Auto-renewed; update land records annually",
        "official_link": "https://pmkisan.gov.in/", "application_portal": "https://pmkisan.gov.in/",
        "target_audience": "Farmer families", "state_specific": "all",
        "tags": ["farmer", "income support", "agriculture", "subsidy"],
        "keywords": "kisan farmer income support agriculture direct benefit transfer dbt crop",
        "is_trending": True,
    },
    {
        "code": "PM-FBY", "name": "PM Fasal Bima Yojana",
        "short_name": "PM-FBY", "ministry": "Ministry of Agriculture & Farmers Welfare",
        "level": "central", "category": "farmer",
        "description": "Crop insurance against natural calamities, pests and diseases. Farmers pay a nominal premium.",
        "benefits": [{"label": "Crop insurance", "detail": "Covers yield loss from natural calamities", "value": "Sum insured"},
                     {"label": "Premium", "detail": "As low as 1.5%-2% of sum insured", "value": "Low premium"}],
        "eligibility_rules": [
            R(field="is_farmer", op="boolean", value=True, weight=40,
              label="You are a farmer", improve="Scheme covers cultivators who grow notified crops."),
            R(field="land_owned_acres", op="gte", value=0, weight=15, label="You own/lease cultivable land"),
            R(field="land_owned_acres", op="lte", value=40, weight=5, label="Land holding is within scheme limits"),
            R(field="age", op="gte", value=18, weight=5, label="You are 18 or older"),
            R(field="state", op="ne", value="", weight=5, label="State is enrolled in the scheme"),
        ],
        "required_documents": ["Aadhaar", "Land records (Patta/RoR)", "Crop details / sowing certificate", "Bank passbook"],
        "amount": "Sum insured up to ₹2 lakh/acre", "amount_max": 200000, "duration": "Per crop season",
        "application_time": "20 minutes", "renewal_policy": "Enroll every season before cut-off",
        "official_link": "https://pmfby.gov.in/", "application_portal": "https://pmfby.gov.in/",
        "target_audience": "Farmers", "state_specific": "all",
        "tags": ["farmer", "insurance", "crop", "risk"],
        "keywords": "crop insurance fasal bima farmer premium natural calamity", "is_trending": True,
    },
    {
        "code": "KCC", "name": "Kisan Credit Card Scheme",
        "short_name": "KCC", "ministry": "Ministry of Agriculture & Farmers Welfare",
        "level": "central", "category": "farmer",
        "description": "Provides affordable crop credit to farmers through banks with interest subvention.",
        "benefits": [{"label": "Credit limit", "detail": "Based on land holding & crop pattern", "value": "Up to ₹3 lakh"},
                     {"label": "Interest subvention", "detail": "Effective interest as low as 4%", "value": "4% p.a."}],
        "eligibility_rules": [
            R(field="is_farmer", op="boolean", value=True, weight=40,
              label="You are a farmer", improve="Scheme covers all farmers with cultivable land."),
            R(field="age", op="gte", value=18, weight=10, label="You are 18 or older"),
            R(any=[R(field="cibil_score", op="gte", value=650), R(field="has_savings_account", op="eq", value=True)], weight=15,
              label="You have a bank relationship / good credit standing",
              improve="Maintain a savings account and a healthy CIBIL score."),
            R(field="annual_income", op="lt", value=5000000, weight=5, label="Income within lending norms"),
        ],
        "required_documents": ["Aadhaar", "Land records", "Bank passbook", "Passport photo"],
        "amount": "Up to ₹3 lakh", "amount_max": 300000, "duration": "Revolving credit",
        "application_time": "15 minutes", "renewal_policy": "Renew every 5 years",
        "official_link": "https://www.kcc.gov.in/", "application_portal": "https://www.kcc.gov.in/",
        "target_audience": "Farmers", "state_specific": "all",
        "tags": ["farmer", "loan", "credit", "agriculture"],
        "keywords": "kisan credit card loan crop credit bank farmer", "is_trending": False,
    },
    {
        "code": "PM-KMDY", "name": "PM Kisan Maan Dhan Yojana",
        "short_name": "PM-KMDY", "ministry": "Ministry of Agriculture & Farmers Welfare",
        "level": "central", "category": "pension",
        "description": "Pension of ₹3,000/month for small and marginal farmers after 60 years of age.",
        "benefits": [{"label": "Pension", "detail": "₹3,000/month on turning 60", "value": "₹3,000/month"},
                     {"label": "Premium", "detail": "₹55-₹200/month based on entry age", "value": "Low premium"}],
        "eligibility_rules": [
            R(field="is_farmer", op="boolean", value=True, weight=30,
              label="You are a farmer", improve="Scheme is for land-holding farmers."),
            R(field="is_marginal_farmer", op="boolean", value=True, weight=30,
              label="You are a small/marginal farmer (< 2 hectares)",
              improve="Must own less than 2 hectares of land."),
            R(field="age", op="between", value=[18, 40], weight=25,
              label="You are aged 18-40 (entering the scheme)",
              improve="Enroll before age 40 for full benefits."),
            R(field="annual_income", op="lt", value=300000, weight=5, label="Income below ₹3 lakh"),
        ],
        "required_documents": ["Aadhaar", "Land records", "Bank passbook", "Age proof"],
        "amount": "₹3,000/month pension", "amount_max": 36000, "duration": "Lifelong after 60",
        "application_time": "15 minutes", "renewal_policy": "Contribute till age 60",
        "official_link": "https://www.pmkmy.gov.in/", "application_portal": "https://www.pmkmy.gov.in/",
        "target_audience": "Small & marginal farmers", "state_specific": "all",
        "tags": ["farmer", "pension", "senior", "social security"],
        "keywords": "kisan pension maan dhan farmer social security old age", "is_trending": False,
    },
    {
        "code": "PM-KUSUM", "name": "PM-KUSUM Solar Pump Scheme",
        "short_name": "PM-KUSUM", "ministry": "Ministry of New & Renewable Energy",
        "level": "central", "category": "energy",
        "description": "Subsidy of up to 60% for farmers to install solar pumps for irrigation.",
        "benefits": [{"label": "Subsidy", "detail": "Up to 60% of pump cost", "value": "Up to 60%"},
                     {"label": "Solar power", "detail": "Free power for irrigation + sell surplus", "value": "Free power"}],
        "eligibility_rules": [
            R(field="is_farmer", op="boolean", value=True, weight=35,
              label="You are a farmer", improve="Only farmers can avail this."),
            R(any=[R(field="land_owned_acres", op="gte", value=1), R(field="is_marginal_farmer", op="eq", value=True)], weight=20,
              label="You have at least 1 acre of cultivable land"),
            R(field="annual_income", op="lt", value=800000, weight=10, label="Income below ₹8 lakh"),
            R(field="age", op="gte", value=18, weight=5, label="You are 18 or older"),
            R(field="state", op="ne", value="", weight=5, label="Resident of participating state"),
        ],
        "required_documents": ["Aadhaar", "Land records", "Subsidy application form", "Bank passbook", "Feasibility report"],
        "amount": "Up to ₹4.8 lakh subsidy", "amount_max": 480000, "duration": "One-time install",
        "application_time": "30 minutes", "renewal_policy": "One-time installation",
        "official_link": "https://mnre.gov.in/solar/schemes/", "application_portal": "https://pmkusum.mnre.gov.in/",
        "target_audience": "Farmers", "state_specific": "all",
        "tags": ["farmer", "energy", "solar", "subsidy"],
        "keywords": "solar pump kusum irrigation renewable subsidy farmer", "is_trending": False,
    },
    {
        "code": "PM-MUDRA", "name": "Pradhan Mantri Mudra Yojana",
        "short_name": "PM-MUDRA", "ministry": "Ministry of Finance",
        "level": "central", "category": "msme",
        "description": "Loans up to ₹10 lakh for micro/small businesses without collateral under three categories.",
        "benefits": [{"label": "Loan", "detail": "Shishu ₹50k, Kishor ₹5L, Tarun ₹10L", "value": "Up to ₹10 lakh"},
                     {"label": "Collateral", "detail": "No collateral required", "value": "None"}],
        "eligibility_rules": [
            R(field="is_entrepreneur", op="boolean", value=True, weight=30,
              label="You run a business or plan to start one",
              improve="Start a small business to qualify for Mudra loans."),
            R(field="age", op="gte", value=18, weight=15, label="You are 18 or older"),
            R(field="annual_income", op="lt", value=2500000, weight=10, label="Income below ₹25 lakh"),
            R(field="business_years", op="gte", value=0, weight=5, label="Business (or new venture) qualifies"),
            R(field="has_savings_account", op="boolean", value=True, weight=10,
              label="You have a bank account", improve="Open a bank account to receive the loan."),
        ],
        "required_documents": ["Aadhaar", "PAN card", "Business plan / proof of business", "Bank account", "Quotation (optional)"],
        "amount": "Up to ₹10 lakh", "amount_max": 1000000, "duration": "3-5 years",
        "application_time": "20 minutes", "renewal_policy": "Fresh loan each cycle",
        "official_link": "https://www.mudra.org.in/", "application_portal": "https://www.mudra.org.in/",
        "target_audience": "MSMEs, small businesses, startups", "state_specific": "all",
        "tags": ["msme", "loan", "business", "startup", "women"],
        "keywords": "mudra loan micro small business msme collateral free woman", "is_trending": True,
    },
    {
        "code": "PM-VISHWAKARMA", "name": "PM Vishwakarma Yojana",
        "short_name": "PM-VK", "ministry": "Ministry of Micro, Small & Medium Enterprises",
        "level": "central", "category": "msme",
        "description": "Skill vouchers, tools and collateral-free loans for traditional artisans and craftspeople.",
        "benefits": [{"label": "Skill training", "detail": "Free 5-7 day training + stipend", "value": "Free training"},
                     {"label": "Loan", "detail": "First loan ₹50k, second ₹1 lakh at 5%", "value": "Up to ₹1 lakh"}],
        "eligibility_rules": [
            R(field="occupation", op="in", value=["self-employed", "business"], weight=30,
              label="You are self-employed / artisan", improve="Artisans (carpenter, potter, tailor etc.) qualify."),
            R(field="age", op="gte", value=18, weight=15, label="You are 18 or older"),
            R(field="annual_income", op="lt", value=1500000, weight=10, label="Income below ₹15 lakh"),
            R(field="education", op="ne", value="graduate", weight=5, label="Not a graduate of a technical institute"),
            R(field="has_savings_account", op="boolean", value=True, weight=10,
              label="You have a bank account", improve="Open a bank account to receive support."),
        ],
        "required_documents": ["Aadhaar", "PAN card", "Proof of artisan work", "Bank passbook"],
        "amount": "Up to ₹1 lakh loan + training", "amount_max": 100000, "duration": "2 loans over scheme period",
        "application_time": "20 minutes", "renewal_policy": "Second loan after first is repaid",
        "official_link": "https://pmvishwakarma.gov.in/", "application_portal": "https://pmvishwakarma.gov.in/",
        "target_audience": "Traditional artisans", "state_specific": "all",
        "tags": ["msme", "artisan", "skill", "loan"],
        "keywords": "vishwakarma artisan craft skill loan carpenter tailor", "is_trending": False,
    },
    {
        "code": "STANDUP-INDIA", "name": "Stand Up India",
        "short_name": "Stand-Up", "ministry": "Ministry of Finance",
        "level": "central", "category": "msme",
        "description": "Bank loans between ₹10 lakh and ₹1 crore for women, SC and ST entrepreneurs.",
        "benefits": [{"label": "Loan", "detail": "₹10 lakh - ₹1 crore", "value": "Up to ₹1 crore"},
                     {"label": "Eligible", "detail": "For women & SC/ST entrepreneurs", "value": "Targeted"}],
        "eligibility_rules": [
            R(any=[R(field="is_woman", op="eq", value=True), R(field="category", op="in", value=["sc", "st"])], weight=35,
              label="You are a woman OR from SC/ST category",
              improve="Scheme targets women, SC and ST entrepreneurs."),
            R(field="is_entrepreneur", op="boolean", value=True, weight=20,
              label="You run or will start a business", improve="Greenfield ventures qualify."),
            R(field="age", op="gte", value=18, weight=10, label="You are 18 or older"),
            R(field="business_years", op="between", value=[0, 10], weight=5,
              label="Business is under 10 years old"),
            R(field="has_savings_account", op="boolean", value=True, weight=10,
              label="You have a bank account", improve="Open a bank account to receive support."),
        ],
        "required_documents": ["Aadhaar", "PAN card", "Caste certificate (SC/ST)", "Business plan", "Bank account"],
        "amount": "₹10 lakh - ₹1 crore", "amount_max": 10000000, "duration": "5-7 years",
        "application_time": "30 minutes", "renewal_policy": "One-time per borrower",
        "official_link": "https://www.standupmitra.in/", "application_portal": "https://www.standupmitra.in/",
        "target_audience": "Women, SC & ST entrepreneurs", "state_specific": "all",
        "tags": ["msme", "women", "sc", "st", "loan", "entrepreneur"],
        "keywords": "stand up india women sc st entrepreneur loan startup", "is_trending": False,
    },
    {
        "code": "SISF", "name": "Startup India Seed Fund Scheme",
        "short_name": "SISF", "ministry": "DPIIT, Ministry of Commerce & Industry",
        "level": "central", "category": "startup",
        "description": "Seed funding up to ₹20 lakh for idea-stage and early-stage startups through incubators.",
        "benefits": [{"label": "Seed fund", "detail": "₹10-20 lakh for early ventures", "value": "Up to ₹20 lakh"},
                     {"label": "Incubation", "detail": "Mentorship through DPIIT incubators", "value": "Mentorship"}],
        "eligibility_rules": [
            R(field="business_type", op="in", value=["startup", "services", "manufacturing"], weight=30,
              label="You run a scalable startup/tech business",
              improve="Register your startup with DPIIT to qualify."),
            R(field="is_entrepreneur", op="boolean", value=True, weight=15, label="You are an entrepreneur"),
            R(field="business_years", op="lt", value=10, weight=15,
              label="Company is under 10 years old", improve="Startups under 10 years qualify."),
            R(field="annual_income", op="lt", value=5000000, weight=5, label="Company turnover under ₹50 lakh"),
            R(field="education", op="in", value=["graduate", "postgraduate", "diploma"], weight=10,
              label="You hold a degree", improve="Higher education is preferred for seed grants."),
        ],
        "required_documents": ["Incorporation certificate", "DPIIT recognition", "Pitch deck", "Financial projections", "Founder IDs"],
        "amount": "Up to ₹20 lakh", "amount_max": 2000000, "duration": "Seed stage",
        "application_time": "45 minutes", "renewal_policy": "One-time per startup",
        "official_link": "https://www.startupindia.gov.in/", "application_portal": "https://www.startupindia.gov.in/",
        "target_audience": "Startups", "state_specific": "all",
        "tags": ["startup", "funding", "seed", "entrepreneur"],
        "keywords": "startup india seed fund dpiit incubation funding", "is_trending": True,
    },
    {
        "code": "PMKVY", "name": "Pradhan Mantri Kaushal Vikas Yojana",
        "short_name": "PMKVY", "ministry": "Ministry of Skill Development",
        "level": "central", "category": "skill",
        "description": "Free skill training and certification for youth to boost employability.",
        "benefits": [{"label": "Training", "detail": "Free certified skill training", "value": "Free"},
                     {"label": "Stipend", "detail": "Post-training stipend", "value": "Varies"}],
        "eligibility_rules": [
            R(field="age", op="between", value=[15, 45], weight=30,
              label="You are aged 15-45", improve="Scheme covers working-age youth."),
            R(any=[R(field="education", op="lt", value="graduate"), R(field="occupation", op="in", value=["unemployed", "student", "daily wage"])], weight=25,
              label="School dropout / unemployed youth preferred",
              improve="Unemployed or school-dropout candidates are prioritised."),
            R(field="annual_income", op="lt", value=300000, weight=10, label="Family income below ₹3 lakh"),
            R(field="state", op="ne", value="", weight=5, label="Resident of India"),
        ],
        "required_documents": ["Aadhaar", "Educational certificate", "Bank passbook", "Photograph"],
        "amount": "Free training + certification", "amount_max": 25000, "duration": "3-6 months",
        "application_time": "15 minutes", "renewal_policy": "One-time per candidate",
        "official_link": "https://www.pmkvyofficial.org/", "application_portal": "https://www.pmkvyofficial.org/",
        "target_audience": "Youth (15-45)", "state_specific": "all",
        "tags": ["skill", "youth", "training", "student", "unemployed"],
        "keywords": "kaushal vikas skill training certification youth employability", "is_trending": False,
    },
    {
        "code": "NSP-POSTMATRIC", "name": "National Scholarship Portal - Post Matric",
        "short_name": "NSP-SC/ST", "ministry": "Ministry of Social Justice & Empowerment",
        "level": "central", "category": "scholarship",
        "description": "Post-matric scholarships for SC/ST/OBC and minority students covering fees and maintenance.",
        "benefits": [{"label": "Tuition", "detail": "Full fee reimbursement", "value": "100% fees"},
                     {"label": "Maintenance", "detail": "Monthly stipend for hostellers/day scholars", "value": "Monthly stipend"}],
        "eligibility_rules": [
            R(field="is_student", op="boolean", value=True, weight=35,
              label="You are a student", improve="Applicable to students in Class 11+ or higher education."),
            R(any=[R(field="category", op="in", value=["sc", "st", "obc", "minority"]),
                   R(field="category", op="in", value=["sc", "st"])], weight=30,
              label="You belong to SC/ST/OBC/minority category",
              improve="Hold a valid category certificate."),
            R(field="annual_income", op="lte", value=250000, weight=15,
              label="Family income below ₹2.5 lakh",
              improve="Family income must be under ₹2.5 lakh for SC/ST."),
            R(field="age", op="gte", value=15, weight=5, label="You are 15 or older"),
            R(field="education", op="in", value=["hs", "diploma", "graduate", "postgraduate"], weight=5,
              label="You are in Class 11 or above"),
        ],
        "required_documents": ["Aadhaar", "Caste certificate", "Income certificate", "Previous year marksheet", "Bank account (DBT)"],
        "amount": "Full fees + stipend", "amount_max": 200000, "duration": "Per academic year",
        "application_time": "25 minutes", "renewal_policy": "Re-apply each academic year",
        "official_link": "https://scholarships.gov.in/", "application_portal": "https://scholarships.gov.in/",
        "target_audience": "SC/ST/OBC/minority students", "state_specific": "all",
        "tags": ["student", "scholarship", "sc", "st", "education"],
        "keywords": "scholarship post matric nsp sc st obc student fees stipend", "is_trending": False,
    },
    {
        "code": "PMAY-G", "name": "Pradhan Mantri Awas Yojana - Gramin",
        "short_name": "PMAY-G", "ministry": "Ministry of Rural Development",
        "level": "central", "category": "housing",
        "description": "Financial assistance to build pucca houses with basic amenities for rural landless households.",
        "benefits": [{"label": "Housing grant", "detail": "₹1.2 lakh in plain areas", "value": "₹1.2 lakh"},
                     {"label": "Amenities", "detail": "Toilet, LPG, electricity linkage", "value": "Included"}],
        "eligibility_rules": [
            R(field="has_house", op="boolean", value=False, weight=35,
              label="Your family does not own a pucca house",
              improve="Only homeless or kutcha-house families qualify."),
            R(field="has_ration_card", op="boolean", value=True, weight=15,
              label="You hold a BPL ration card",
              improve="Enrol for a ration card under the NFSA."),
            R(field="annual_income", op="lt", value=300000, weight=15,
              label="Family income below ₹3 lakh", improve="Keep family income under the cap."),
            R(field="is_farmer", op="boolean", value=False, weight=5,
              label="Landless or marginal land holding"),
            R(field="age", op="gte", value=18, weight=5, label="You are 18 or older"),
        ],
        "required_documents": ["Aadhaar", "Ration card", "Income certificate", "Land documents", "Bank passbook"],
        "amount": "₹1.2 lakh", "amount_max": 120000, "duration": "One-time grant",
        "application_time": "30 minutes", "renewal_policy": "One-time per household",
        "official_link": "https://pmayg.nic.in/", "application_portal": "https://pmayg.nic.in/",
        "target_audience": "Rural landless households", "state_specific": "all",
        "tags": ["housing", "rural", "bpl", "scheme"],
        "keywords": "awas housing gramin rural house grant bpl", "is_trending": False,
    },
    {
        "code": "PMUJJWALA", "name": "Pradhan Mantri Ujjwala Yojana",
        "short_name": "Ujjwala", "ministry": "Ministry of Petroleum & Natural Gas",
        "level": "central", "category": "energy",
        "description": "Free LPG connections to poor households, prioritising women.",
        "benefits": [{"label": "LPG connection", "detail": "Free connection + first refill + stove", "value": "Free"},
                     {"label": "Target", "detail": "BPL women-led households", "value": "Household"}],
        "eligibility_rules": [
            R(field="has_lpg_connection", op="boolean", value=False, weight=35,
              label="Your household has no existing LPG connection",
              improve="Eligible only if no LPG in the household."),
            R(any=[R(field="is_woman", op="eq", value=True), R(field="gender", op="in", value=["female", "other"])], weight=25,
              label="Adult woman in the household",
              improve="Connection is issued to an adult woman."),
            R(any=[R(field="has_ration_card", op="eq", value=True),
                   R(field="annual_income", op="lt", value=120000)], weight=20,
              label="BPL / low-income household (income below ₹1.2 lakh)",
              improve="Enrol for a ration card or keep income below the threshold."),
            R(field="age", op="gte", value=18, weight=5, label="Applicant is 18 or older"),
        ],
        "required_documents": ["Aadhaar", "Ration card / income certificate", "Bank passbook", "Address proof"],
        "amount": "Free connection (~₹1,600)", "amount_max": 1600, "duration": "One-time",
        "application_time": "15 minutes", "renewal_policy": "One-time connection",
        "official_link": "https://www.pmujjwalayojana.com/", "application_portal": "https://www.pmujjwalayojana.com/",
        "target_audience": "BPL households, women", "state_specific": "all",
        "tags": ["energy", "women", "bpl", "household"],
        "keywords": "ujjwala lpg gas connection women bpl household", "is_trending": False,
    },
    {
        "code": "SSY", "name": "Sukanya Samriddhi Yojana",
        "short_name": "SSY", "ministry": "Ministry of Finance",
        "level": "central", "category": "savings",
        "description": "High-interest savings scheme for the girl child, with income-tax benefits.",
        "benefits": [{"label": "Interest", "detail": "8.2% p.a. compounded annually", "value": "8.2% p.a."},
                     {"label": "Tax", "detail": "EEE status - fully tax free", "value": "Tax-free"}],
        "eligibility_rules": [
            R(field="children_girl", op="boolean", value=True, weight=40,
              label="You have a girl child (below 10 years)",
              improve="Scheme is for a girl child under 10; open before her 10th birthday."),
            R(field="age", op="gte", value=18, weight=10, label="You are 18 or older (guardian)"),
            R(field="has_savings_account", op="boolean", value=True, weight=10,
              label="You have a bank account", improve="Open a bank account to deposit."),
            R(field="annual_income", op="lt", value=1800000, weight=5, label="Income within investing norms"),
        ],
        "required_documents": ["Girl child birth certificate", "Aadhaar", "Guardian bank account"],
        "amount": "₹250 - ₹1.5 lakh/yr", "amount_max": 150000, "duration": "21 years / till marriage",
        "application_time": "15 minutes", "renewal_policy": "Annual deposits",
        "official_link": "https://www.indiapost.gov.in/", "application_portal": "https://www.indiapost.gov.in/",
        "target_audience": "Girl child (below 10)", "state_specific": "all",
        "tags": ["savings", "girl child", "investment", "tax"],
        "keywords": "sukanya samriddhi girl child savings interest post office", "is_trending": False,
    },
    {
        "code": "PMJAY", "name": "Ayushman Bharat PM-JAY",
        "short_name": "PM-JAY", "ministry": "Ministry of Health & Family Welfare",
        "level": "central", "category": "health",
        "description": "Free health insurance of ₹5 lakh per family per year for secondary and tertiary hospitalisation.",
        "benefits": [{"label": "Insurance cover", "detail": "₹5 lakh per family per year", "value": "₹5 lakh"},
                     {"label": "Hospitalisation", "detail": "Covers 1,900+ packages", "value": "Cashless"}],
        "eligibility_rules": [
            R(any=[R(field="has_ration_card", op="eq", value=True),
                   R(field="annual_income", op="lte", value=250000)], weight=40,
              label="You are a deprived / BPL household (income ≤ ₹2.5 lakh)",
              improve="Enrol for a ration card; the SECC database determines eligibility."),
            R(field="age", op="gte", value=0, weight=5, label="Applies to all family members"),
            R(field="state", op="ne", value="", weight=5, label="Resident of India"),
        ],
        "required_documents": ["Aadhaar", "Ration card / SECC database", "Bank account"],
        "amount": "₹5 lakh coverage", "amount_max": 500000, "duration": "Annual, renews",
        "application_time": "10 minutes", "renewal_policy": "Automatic renewal",
        "official_link": "https://pmjay.gov.in/", "application_portal": "https://pmjay.gov.in/",
        "target_audience": "BPL families", "state_specific": "all",
        "tags": ["health", "insurance", "bpl", "family"],
        "keywords": "ayushman bharat health insurance hospital cashless bpl", "is_trending": True,
    },
    {
        "code": "PMSYM", "name": "PM Shram Yogi Maan-dhan",
        "short_name": "PM-SYM", "ministry": "Ministry of Labour & Employment",
        "level": "central", "category": "pension",
        "description": "Monthly pension of ₹3,000 after 60 for unorganised workers aged 18-40.",
        "benefits": [{"label": "Pension", "detail": "₹3,000/month after age 60", "value": "₹3,000/month"},
                     {"label": "Premium", "detail": "₹55-₹200/month", "value": "Low premium"}],
        "eligibility_rules": [
            R(field="age", op="between", value=[18, 40], weight=30,
              label="You are aged 18-40", improve="Enrol before age 40."),
            R(field="employment_type", op="in", value=["unorganised", "self-employed", "none"], weight=25,
              label="You work in the unorganised sector",
              improve="Casual/daily-wage and informal workers qualify."),
            R(field="annual_income", op="lt", value=1500000, weight=10, label="Monthly income below ₹15,000"),
            R(field="has_savings_account", op="boolean", value=True, weight=10,
              label="You have a bank account", improve="Open a savings account to enrol."),
        ],
        "required_documents": ["Aadhaar", "Bank passbook", "Mobile number"],
        "amount": "₹3,000/month pension", "amount_max": 36000, "duration": "Lifelong after 60",
        "application_time": "10 minutes", "renewal_policy": "Contribute till 60",
        "official_link": "https://maandhan.in/", "application_portal": "https://maandhan.in/",
        "target_audience": "Unorganised workers (18-40)", "state_specific": "all",
        "tags": ["pension", "unorganised", "social security", "worker"],
        "keywords": "shram yogi pension unorganised worker maandhan social security", "is_trending": False,
    },
    {
        "code": "PMJJBY", "name": "PM Jeevan Jyoti Bima Yojana",
        "short_name": "PMJJBY", "ministry": "Ministry of Finance",
        "level": "central", "category": "insurance",
        "description": "Life insurance cover of ₹2 lakh for ₹436 per year for bank account holders aged 18-50.",
        "benefits": [{"label": "Life cover", "detail": "₹2 lakh on death", "value": "₹2 lakh"},
                     {"label": "Premium", "detail": "₹436/year auto-debited", "value": "₹436/yr"}],
        "eligibility_rules": [
            R(field="age", op="between", value=[18, 50], weight=35,
              label="You are aged 18-50", improve="Cover ends at age 55."),
            R(field="has_savings_account", op="boolean", value=True, weight=25,
              label="You hold a savings bank account", improve="Open a bank account and give standing instructions."),
            R(field="annual_income", op="lt", value=3000000, weight=5, label="Income within norms"),
        ],
        "required_documents": ["Aadhaar", "Bank passbook"],
        "amount": "₹2 lakh cover", "amount_max": 200000, "duration": "Annual, auto-renew",
        "application_time": "10 minutes", "renewal_policy": "Auto-debit renewal",
        "official_link": "https://www.jansuraksha.gov.in/", "application_portal": "https://www.jansuraksha.gov.in/",
        "target_audience": "Bank account holders 18-50", "state_specific": "all",
        "tags": ["insurance", "life", "bank"],
        "keywords": "jeevan jyoti life insurance bank account premium", "is_trending": False,
    },
    {
        "code": "PMSBY", "name": "PM Suraksha Bima Yojana",
        "short_name": "PMSBY", "ministry": "Ministry of Finance",
        "level": "central", "category": "insurance",
        "description": "Accident insurance of ₹2 lakh for ₹20 per year for bank account holders aged 18-70.",
        "benefits": [{"label": "Accident cover", "detail": "₹2 lakh on accidental death/disability", "value": "₹2 lakh"},
                     {"label": "Premium", "detail": "₹20/year", "value": "₹20/yr"}],
        "eligibility_rules": [
            R(field="age", op="between", value=[18, 70], weight=35,
              label="You are aged 18-70", improve="Cover for account holders aged 18-70."),
            R(field="has_savings_account", op="boolean", value=True, weight=25,
              label="You hold a savings bank account", improve="Open a bank account to enrol."),
        ],
        "required_documents": ["Aadhaar", "Bank passbook"],
        "amount": "₹2 lakh cover", "amount_max": 200000, "duration": "Annual, auto-renew",
        "application_time": "5 minutes", "renewal_policy": "Auto-debit renewal",
        "official_link": "https://www.jansuraksha.gov.in/", "application_portal": "https://www.jansuraksha.gov.in/",
        "target_audience": "Bank account holders 18-70", "state_specific": "all",
        "tags": ["insurance", "accident", "bank"],
        "keywords": "suraksha bima accident insurance bank account", "is_trending": False,
    },
    {
        "code": "APY", "name": "Atal Pension Yojana",
        "short_name": "APY", "ministry": "Ministry of Finance",
        "level": "central", "category": "pension",
        "description": "Guaranteed pension of ₹1,000-₹5,000/month after 60 for subscribers aged 18-40.",
        "benefits": [{"label": "Pension", "detail": "₹1,000-₹5,000/month after 60", "value": "Up to ₹5,000"},
                     {"label": "Guaranteed", "detail": "Government-backed return", "value": "Guaranteed"}],
        "eligibility_rules": [
            R(field="age", op="between", value=[18, 40], weight=40,
              label="You are aged 18-40", improve="Join before 40 for guaranteed pension."),
            R(field="has_savings_account", op="boolean", value=True, weight=20,
              label="You hold a savings bank account", improve="Open a bank account to enrol."),
            R(field="employment_type", op="ne", value="organised", weight=10,
              label="You are not a salaried taxpayer"),
        ],
        "required_documents": ["Aadhaar", "Bank passbook", "Mobile number"],
        "amount": "₹1,000-₹5,000/month pension", "amount_max": 60000, "duration": "Lifelong after 60",
        "application_time": "10 minutes", "renewal_policy": "Contribute till 60",
        "official_link": "https://www.apy.gov.in/", "application_portal": "https://www.apy.gov.in/",
        "target_audience": "Citizens 18-40", "state_specific": "all",
        "tags": ["pension", "savings", "retirement"],
        "keywords": "atal pension retirement savings guaranteed monthly", "is_trending": False,
    },
    {
        "code": "IGNWPS", "name": "Indira Gandhi National Widow Pension",
        "short_name": "IGNWPS", "ministry": "Ministry of Rural Development",
        "level": "central", "category": "pension",
        "description": "Pension for widows aged 40-59 from BPL households under the NSAP.",
        "benefits": [{"label": "Pension", "detail": "₹300/month + state top-up", "value": "₹300+/month"},
                     {"label": "Target", "detail": "BPL widows aged 40-59", "value": "BPL widows"}],
        "eligibility_rules": [
            R(field="is_widow", op="boolean", value=True, weight=40,
              label="You are a widow", improve="Provide spouse death certificate."),
            R(field="age", op="between", value=[40, 59], weight=20,
              label="You are aged 40-59", improve="After 60 you migrate to the old-age pension."),
            R(any=[R(field="has_ration_card", op="eq", value=True),
                   R(field="annual_income", op="lt", value=300000)], weight=15,
              label="You are from a BPL household"),
            R(field="gender", op="in", value=["female"], weight=5, label="Female applicant"),
        ],
        "required_documents": ["Aadhaar", "Spouse death certificate", "BPL/ration card", "Bank passbook"],
        "amount": "₹300-₹500/month + state top-up", "amount_max": 6000, "duration": "Lifelong",
        "application_time": "20 minutes", "renewal_policy": "Auto-continues",
        "official_link": "https://nsap.nic.in/", "application_portal": "https://nsap.nic.in/",
        "target_audience": "BPL widows 40-59", "state_specific": "all",
        "tags": ["pension", "women", "widow", "bpl", "social security"],
        "keywords": "widow pension indira gandhi nsap bpl", "is_trending": False,
    },
    {
        "code": "IGNOAPS", "name": "Indira Gandhi National Old Age Pension",
        "short_name": "IGNOAPS", "ministry": "Ministry of Rural Development",
        "level": "central", "category": "pension",
        "description": "Old-age pension for BPL citizens aged 60 and above under NSAP.",
        "benefits": [{"label": "Pension", "detail": "₹200/month + state top-up", "value": "₹200+/month"},
                     {"label": "Target", "detail": "BPL seniors 60+", "value": "BPL seniors"}],
        "eligibility_rules": [
            R(field="age", op="gte", value=60, weight=40,
              label="You are 60 or older", improve="Reaches full benefit after 60."),
            R(any=[R(field="has_ration_card", op="eq", value=True),
                   R(field="annual_income", op="lt", value=300000)], weight=20,
              label="You are from a BPL household"),
            R(field="state", op="ne", value="", weight=5, label="Resident of India"),
        ],
        "required_documents": ["Aadhaar", "BPL/ration card", "Age proof", "Bank passbook"],
        "amount": "₹200-₹500/month + state top-up", "amount_max": 6000, "duration": "Lifelong",
        "application_time": "20 minutes", "renewal_policy": "Auto-continues",
        "official_link": "https://nsap.nic.in/", "application_portal": "https://nsap.nic.in/",
        "target_audience": "BPL senior citizens 60+", "state_specific": "all",
        "tags": ["pension", "senior", "bpl", "social security"],
        "keywords": "old age pension indira gandhi nsap senior citizen bpl", "is_trending": False,
    },
    {
        "code": "RYTHU-BHAROSA", "name": "Rythu Bharosa (Andhra Pradesh)",
        "short_name": "Rythu Bharosa", "ministry": "Government of Andhra Pradesh",
        "level": "state", "category": "farmer",
        "description": "AP state income support of ₹13,500/year to all eligible farmers, in addition to PM-KISAN.",
        "benefits": [{"label": "Income support", "detail": "₹13,500 per year (incl. PM-KISAN ₹6,000)", "value": "₹13,500/yr"},
                     {"label": "Coverage", "detail": "All AP farmer families", "value": "All farmers"}],
        "eligibility_rules": [
            R(field="state", op="eq", value="Andhra Pradesh", weight=40,
              label="You reside in Andhra Pradesh", improve="Scheme is exclusive to AP residents."),
            R(field="is_farmer", op="boolean", value=True, weight=25,
              label="You are a farmer", improve="Cultivators with land in AP qualify."),
            R(field="annual_income", op="lt", value=300000, weight=10,
              label="Income below ₹3 lakh", improve="Scheme targets small & marginal farmers."),
            R(field="age", op="gte", value=18, weight=5, label="You are 18 or older"),
        ],
        "required_documents": ["Aadhaar", "Land records (Adangal/Pahani)", "Bank passbook", "Rythu Bharosa enrolment"],
        "amount": "₹13,500/year", "amount_max": 13500, "duration": "Annual",
        "application_time": "10 minutes", "renewal_policy": "Verified every year",
        "official_link": "https://www.rythubharosa.ap.gov.in/", "application_portal": "https://www.rythubharosa.ap.gov.in/",
        "target_audience": "AP farmers", "state_specific": "Andhra Pradesh",
        "tags": ["farmer", "andhra pradesh", "income support", "state"],
        "keywords": "rythu bharosa ap farmer income support andhra pradesh", "is_trending": False,
    },
    {
        "code": "YSR-CHEYUTHA", "name": "YSR Cheyutha (Andhra Pradesh)",
        "short_name": "YSR Cheyutha", "ministry": "Government of Andhra Pradesh",
        "level": "state", "category": "women",
        "description": "Financial assistance of ₹18,750/year for women aged 45-60 from backward classes in AP.",
        "benefits": [{"label": "Assistance", "detail": "₹18,750 per year for 4 years", "value": "₹18,750/yr"},
                     {"label": "Target", "detail": "BC/SC/ST minority women 45-60", "value": "Targeted"}],
        "eligibility_rules": [
            R(field="state", op="eq", value="Andhra Pradesh", weight=40,
              label="You reside in Andhra Pradesh"),
            R(field="is_woman", op="eq", value=True, weight=25,
              label="You are a woman", improve="Scheme is for women aged 45-60."),
            R(field="age", op="between", value=[45, 60], weight=20,
              label="You are aged 45-60", improve="Eligibility window is 45-60 years."),
            R(any=[R(field="category", op="in", value=["sc", "st", "obc", "minority"]),
                   R(field="has_ration_card", op="eq", value=True)], weight=10,
              label="Backward class / BPL household"),
        ],
        "required_documents": ["Aadhaar", "Category certificate", "Income certificate", "Bank passbook"],
        "amount": "₹18,750/year", "amount_max": 18750, "duration": "4 years",
        "application_time": "15 minutes", "renewal_policy": "Annual",
        "official_link": "https://www.cheyutha.ap.gov.in/", "application_portal": "https://www.cheyutha.ap.gov.in/",
        "target_audience": "AP women 45-60 (BC/SC/ST)", "state_specific": "Andhra Pradesh",
        "tags": ["women", "andhra pradesh", "assistance", "state"],
        "keywords": "ysr cheyutha women andhra pradesh assistance", "is_trending": False,
    },
    {
        "code": "PM-DAKSH", "name": "PM-DAKSH (Skill of SC/ST youth)",
        "short_name": "PM-DAKSH", "ministry": "Ministry of Social Justice & Empowerment",
        "level": "central", "category": "skill",
        "description": "Free skill training, reskilling and entrepreneurship support for SC/ST youth.",
        "benefits": [{"label": "Training", "detail": "Free skill + digital training", "value": "Free"},
                     {"label": "Entrepreneurship", "detail": "Marketing & loan facilitation", "value": "Support"}],
        "eligibility_rules": [
            R(field="category", op="in", value=["sc", "st"], weight=40,
              label="You belong to SC/ST category", improve="Hold a valid caste certificate."),
            R(field="age", op="between", value=[18, 45], weight=20,
              label="You are aged 18-45", improve="Youth aged 18-45 qualify."),
            R(field="annual_income", op="lt", value=800000, weight=10,
              label="Family income below ₹8 lakh"),
        ],
        "required_documents": ["Aadhaar", "Caste certificate", "Educational certificate", "Income certificate"],
        "amount": "Free training", "amount_max": 0, "duration": "Per course",
        "application_time": "15 minutes", "renewal_policy": "Re-apply per course",
        "official_link": "https://pndashk.gov.in/", "application_portal": "https://pndashk.gov.in/",
        "target_audience": "SC/ST youth 18-45", "state_specific": "all",
        "tags": ["skill", "sc", "st", "youth", "training"],
        "keywords": "daksh sc st skill youth training entrepreneurship", "is_trending": False,
    },
    {
        "code": "UJALA-SLK", "name": "UJALA Scheme (LED bulbs)",
        "short_name": "UJALA", "ministry": "Ministry of Power",
        "level": "central", "category": "energy",
        "description": "Subsidised LED bulbs and fans for households to cut electricity bills.",
        "benefits": [{"label": "LED bulbs", "detail": "9W LED at ₹70-110", "value": "Subsidised"},
                     {"label": "Savings", "detail": "Up to ₹450/year per household", "value": "Energy saving"}],
        "eligibility_rules": [
            R(field="age", op="gte", value=18, weight=20, label="You are 18 or older"),
            R(field="state", op="ne", value="", weight=10, label="Resident of India"),
        ],
        "required_documents": ["Aadhaar", "Electricity bill"],
        "amount": "Subsidised appliances", "amount_max": 0, "duration": "One-time",
        "application_time": "10 minutes", "renewal_policy": "One-time",
        "official_link": "https://www.ujala.gov.in/", "application_portal": "https://www.ujala.gov.in/",
        "target_audience": "All households", "state_specific": "all",
        "tags": ["energy", "household", "savings"],
        "keywords": "ujala led bulb energy saving electricity", "is_trending": False,
    },
]
